# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
pod 'AFNetworking'
pod 'AFNetworkActivityLogger'

use_frameworks!

target 'swift-news' do

end

target 'swift-newsTests' do

end

