# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'

# 6.3対応
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'

target 'AlmofireSampTests' do

end
